### PR TITLE
Added support for the key property annotation

### PR DESCRIPTION
**Pull request by TSchuermans**
Added support for the key property annotation.
If the annotation isn't present it defaults to the property name.

### CODE REVIEW

**Comment by ikwattro** [comment]
Thanks Tom,
Please add some tests validating your changes. If you are unsure how to add tests, I could add some commits to your PR.

**Comment by TSchuermans** [comment]
@ikwattro I added some small integration tests, can you check if more tests need to be added?

**Comment by ikwattro** [comment]
@TSchuermans That is perfect. All good! Thanks a ton !!!

I will release RC8 with your PR in it

**Comment by ikwattro** [comment]
Released! https://packagist.org/packages/graphaware/neo4j-php-ogm#1.0.0-RC8

**Comment by TSchuermans** [comment]
@ikwattro Woo-hoo!
Btw I also want to implement the multiple labels feature discussed in https://github.com/graphaware/neo4j-php-ogm/issues/54

Do you have any preference as to how it should be implemented?

**Comment by ikwattro** [comment]
This is a bit more complex, as the Metadata should check parent class as well. 

However, note that in general I do not agree with Label inheritance (working with Neo4j everyday I never had this need), we would rather represent inheritance with relationships.

So I would say that for now, use the `@Label` trick.

**Comment by ikwattro** [comment]
@TSchuermans meaning I do not agree doesnt mean it will never be implemented, I just think that the option should be available for inheritance with Labels or Relationships.

**Comment by TSchuermans** [comment]
So if I understand it correctly, you'd rather have multiple relations between 2 nodes to define the context vs using multiple labels on a node.

In that case, it makes perfect sense to me, but due to legacy implementations I'm forced to use multiple labels on a node :(

I'll try opting for the Label annotation on properties, no worries.

**Comment by ikwattro** [comment]
Yes, imagine that you have an Animal hierarchy : 

Animal - Dog - Border Collie

Do you really want to play with labels ? Or have a model like 

(Animal)<-[:PARENT]-(Dog)<-[:PARENT]-(Border Collie) ?

@TSchuermans Note that I am always happy to know what people are doing with Neo4j and PHP, if you dont mind could you share your use case ? Even privately christophe@graphaware.com

Thx

**Comment by TSchuermans** [comment]
We have a system for asset management which uses Neo4j.
Nodes which need to be tracked get an "Asset" label.
But to define extra context they also get a more specific label like "Disk" or "NIC".

This way it's easy for us to query all disks or to give an overview of all assets in the system.
I do agree that this is probably not the right way of handling this problem, but it's something I have to deal with now :D

**Comment by ikwattro** [comment]
Thanks !

**Pull request merged**
