### PR TITLE
XML metadata factories

### PR DESCRIPTION
**Pull request by vbartusevicius**
Did a bit of refactoring to be able to wrap some abstraction around metadata factories. Now it is possible to configure mapping with XML. This allows smoother intergration with Symfony. Proposed XSD schema for XML mappers. Some annotations where not moved becase of lack of documentation.

Help from maintainers to transfer undocumented functionality (i.e.: MappedResult, QueryResult) would be highly appreciated.

### CODE REVIEW

**Comment by vbartusevicius** [comment]
@bachmanm, @ikwattro - could you please take a look at this PR?

P.S. I already sent signed CLA agreement.

**Comment by ikwattro** [comment]
Hi @vbartusevicius 

First, thanks a lot for this PR. I merge it.

I'll just say that there might be changes in an upcoming branch that will need to be addressed. I'll ping you later on that.

Cheers

**Comment by ikwattro** [comment]
If you can add a small section in the docs about "how to do the mapping with xml" this would be very cool. Thanks

**Comment by vbartusevicius** [comment]
@ikwattro - thank you a lot. Will wait for further changes - just keep me in touch :)
In a few days I will update the docs also.

Additionally, could you please upload the `graphaware-mapping.xsd` file to `http://graphaware.com/schemas/ogm/graphaware-mapping.xsd` (or another place you prefer, I will change the code accordingly) to make automatic schema validation by IDE possible?

**Pull request merged**
