### PR TITLE
adjusted test for #106 to verify populated records

### PR DESCRIPTION
**Pull request by cebe**
adjusted test for #106 to verify populated records

records are currently added in reverse order.

### CODE REVIEW

**Comment by cebe** [comment]
Added a fix for #106

**Comment by ikwattro** [comment]
Thanks @cebe . Looks great! I will be able to merge once we receive the CLA. Cheers

**Comment by cebe** [comment]
> Thanks @cebe . Looks great! I will be able to merge once we receive the CLA. Cheers

sent it.

**Comment by cebe** [comment]
cla-bot check should be green already...

**Comment by ikwattro** [comment]
Yes sorry, it doesnt update the status once you submit it but I got it.

Thanks.

**Comment by ikwattro** [comment]
Released in 1.0.0-RC7

**Comment by cebe** [comment]
great, thank you!

**Pull request merged**
