### PR TITLE
remove grave accent

### PR DESCRIPTION
**Pull request by alexandre-le-borgne**
The presence of grave accents around node labels prevents node construction with an inheritance (Child: Parent)

### CODE REVIEW

**Comment by ikwattro** [comment]
@alexandre-le-borgne why would you want to remove escaping backticks ?

**Comment by alexandre-le-borgne** [comment]
when I persist an entity with label "MyEntity" that inherits another entity "MyParent" using the syntax 
/**
 * @OGM\Node(label="MyEntity:MyParent")
 */
it will create a node in Neo4j with the label "`MyEntity:MyParent`" instead of a node with the 2 labels "MyEntity" and "MyParent"

**Comment by ikwattro** [comment]
Right, as mentioned in other issues class level inheritance is not supported yet. You could be able to achieve what you want with the `@Label` property annotation

References : 

Test : https://github.com/graphaware/neo4j-php-ogm/blob/master/tests/Integration/BooleanLabelTest.php#L29

Model : https://github.com/graphaware/neo4j-php-ogm/blob/master/tests/Integration/Models/BooleanLabel/BlogPost.php#L38

**Comment by alexandre-le-borgne** [comment]
Thanks for the advice but i think i will continue to use my fork of removing escaping backticks will not cause a bug. I prefer because it is the syntax used in cypher queries.

Ref: [(https://neo4j.com/docs/developer-manual/current/cypher/clauses/create/#create-create-a-node-with-multiple-labels)](https://neo4j.com/docs/developer-manual/current/cypher/clauses/create/#create-create-a-node-with-multiple-labels)

**Pull request closed without merging**
