### PR TITLE
Removed EntityManager::save

### PR DESCRIPTION
**Pull request by Nyholm**
It is undocumented an unimplemented. A save function does not belong here.

### CODE REVIEW

**Comment by ikwattro** [comment]
@Nyholm I see all your PRs, I will have to check them by the end of the week (too busy right now).

**Comment by Nyholm** [comment]
Thank you. No rush. I would be happy if you reviewed them in November. They are all just minor things.

**Comment by ikwattro** [comment]
Good catch

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
